version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 50
